# Generated by Django 6.0.1 on 2026-03-04 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='is_acive',
            field=models.BooleanField(default=True, verbose_name='Is_active'),
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.categories', verbose_name='subCategory'),
        ),
        migrations.AddField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data updated'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
