# Generated by Django 6.0.1 on 2026-03-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_categories_created_at_categories_is_acive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='is_acive',
            new_name='is_active',
        ),
    ]
